### ISSUE TITLE
[FE] Stworzenie strony 404

### ISSUE THREAD

**Issue by JRRBorkowski** [akademia-envelo-3/moovelo-front#10]
Story
Aktorzy w przypadku błędnego linku zostają przeniesieni na stronę 404.

Dodatkowe informacje:
Po pewnym czasie od wyświetlenia strona przenosi aktorów z powrotem na ekran główny.

Link do Makiet:
https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=0%3A394&t=F55JsmoUlSU5algE-0

Kryteria akceptacji:

- [x]  Stworzenie widoku strony 404
- [x]  Automatyczne przeniesienie aktora na stronę główną

**Comment by PawelJurga** [comment]
@JRRBorkowski jak task przejdzie do QA to oznacz mnie i daj linka do widoku w komentarzu. :)

**Comment by JRRBorkowski** [comment]
@PawelJurga 
[PREVIEW](https://feature-10-stworzenie-strony-404--moovelo-envelo.netlify.app/theme)

**Comment by GBN6** [comment]
@JRRBorkowski Jak mergujesz i usuwasz brancha to preview z netli przestaje działać. Aktualnie strone 404 mozna zobaczyć pod tym [LINKIEM](https://develop--moovelo-envelo.netlify.app/404)

**Comment by PawelJurga** [comment]
- [x] Stworzenie widoku strony 404

   - na stronie prawidłowo rozmieszczono komponenty z makiety

- [ ]  Automatyczne przeniesienie aktora na stronę główną

    - **w wersji testowej nie działa automatyczne przekierowanie na stronę główną**

Sugestia do Taska:
 Warto do widoku dołączyć funkcjonalność, aby czas pięciu sekund był odliczany na ekranie :)

**Comment by JRRBorkowski** [comment]
Jak się przyjrzysz na link to przekierowuje na stronę home, która obecnie jeszcze po prostu nie istnieje. Dlatego cały czas pojawia się 404. Co do odliczania uznaliśmy, że to na ten moment warto się skupić na innych elementach apki.

**Comment by PawelJurga** [comment]
- [x] Automatyczne przeniesienie aktora na stronę główną
  Moje niedopatrzenie. Funkcjonalność działa poprawnie
**Rekomenduję zakończenie taska :)**
