### ISSUE TITLE
[FE] Implementacja funkcjonalności logowania

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#100]
### Informacje
Przed rozpoczęciem taska zrobić research w jaki sposób implementuje się autoryzację z tokenem.
przykład: https://www.positronx.io/angular-jwt-user-authentication-tutorial/

### Endpointy
- `POST api/v1/auth`
```json
{
  "email" : " ",
  "password" : " "
}
```

### Kryteria akceptacji
- [x] Funkcjonalność logowania powinna być w osobnym serwisie
- [x] Przy zalogowaniu serwis powinien zapisywać token w local storage oraz typ konta w storze.
- [x] System rozróżnia czy ktoś jest zalogowany za pomocą obecności tokena w local storage

**Comment by LukaszPietrzykowski16** [comment]
Link do zadania: https://develop--moovelo-envelo.netlify.app/auth (ogólnie task jest bardziej techniczny, niż do QA)
Żeby go przetesować należy mieć zainstalowany json-server-auth (https://www.seijivillafranca.com/post/faking-your-auth-endpoint-using-json-server-auth). 

  "users": [
      "email": "admin@gmail.com",
      "password": "$2a$10$7ZM9.8iMGRSUnIUmguB7s.tC75NP51Mob2khxdnvagWJddbHXnE26",
      "type": "admin",
      "id": 0
    },
    {
      "email": "user@gmail.com",
      "password": "$2a$10$vDgnZZv8Jb8J2d0bWPTqXunIWRhJB4yUbOREwZgws4E38.rK1/yMm",
      "type": "user",
      "id": 1
    }
  ]

Login do usera: 
email: user@gmail.com
hasło: qwerty

Login do admina: 
email: admin@gmail.com
hasło: qwerty

**Comment by PawelJurga** [comment]
- [x]  Funkcjonalność logowania powinna być w osobnym serwisie

- [x] Przy zalogowaniu serwis powinien zapisywać token w local storage oraz typ konta w storze.

- [ ] System rozróżnia czy ktoś jest zalogowany za pomocą obecności tokena w local storage
- **po zalogowaniu aplikacja przenosi użytkownika do zakładki /theme. Po powrocie do okna logowania i ponownym wciśnięciu przycisku "zaloguj" w przeglądarce pojawia się nowy token. Pytanie czy na tym etapie nie powinno być weryfikacji czy użytkownik jest już zalogowany ?. W obecnej chwili za każdym razem otwierana jest nowa sesja i generowany jest nowy token.**

**Comment by LukaszPietrzykowski16** [comment]
Dzięki, za znalezienie błędu związanego z dostępu do panelu zalogowanego użytkownika. 
Dalsza funkcjonalność i naprawa błedów w kwestii tokenów i przekierowań jest już w czasie naprawy w tym tasku: #124

**Comment by PawelJurga** [comment]
**W związku z powyższym komentarzem @LukaszPietrzykowski16  proponuję zakończenie taska i zmergowanie już zaimplementowanych funkcjonalności logowania. Na poźniejszym etapie po wykonaniu zadania #124 przetestuję jeszcze raz całość.**
