### ISSUE TITLE
[FE] Visitor widzą navbar

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#11]
### Story
Visitor chciałbym widzieć odpowiedni navbar i móc z niego korzystać.
### Dodatkowe informacje
Na tym etapie nie dodajemy funkcjonalności przycisku "Zaloguj", "Wyloguj" oraz funkcjonalności powiadomień.
### Makiety
[Makieta](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613157%3A25458&t=cXz2j1BpqGPN1tem-0)
[Design system](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=77%3A432&t=GwaruJDVjcY1V4J0-0)
### Taski blokujące
- #2
### Kryteria akceptacji
- [x] Jako Visitor chciałbym widzieć navbar posiadający logo, tekst "Moovelo" oraz przycisk "Zaloguj"

**Comment by LukaszPietrzykowski16** [comment]
Rozdzieliłem taska na dwa (Visitor widzi navbar oraz user widzi navbar)
