### ISSUE TITLE
[FE][bugfix] Poprawić wyświetlanie pola z liczbą osób w formularzu

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#116]
### Informacje
W momencie wyboru opcji "potwierdzenie obowiązkowe" oraz "orgraniczona liczba miejsc", a następnie odkliknięcie opcji "potwierdzenie obowiązkowe" pole z liczbą miejsc zostaje, a powinno zniknąć i być nieaktywne.

### Linki
- https://develop--moovelo-envelo.netlify.app/create-event/details

### Screeny
![image](https://user-images.githubusercontent.com/79579229/214511521-349cfb3f-c642-4c04-8311-fef14fdcf93c.png)

### Kryteria akceptacji
- [ ] W momencie nieaktywnego przycisku "potwierdzenie obowiązkowe" pole "liczba osób" powinno być niewidoczne
- [ ] W momencie nieaktywnego przycisku "potwierdzenie obowiązkowe" pole "liczba osób" powinno być nieaktywne

**Comment by PawelJurga** [comment]
aktualny link
https://deploy-preview-133--moovelo-envelo.netlify.app/create-event/details
**Retest**

- [x] W momencie nieaktywnego przycisku "potwierdzenie obowiązkowe" pole "liczba osób" powinno być niewidoczne
**Rekomenduję zakończenie taska :)**
