### ISSUE TITLE
[FE][User] Dodać przekierowanie do strony głównej po kliknięciu logo w headerze

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#119]
### Kryteria akceptacji
- [x] Jako User chciałbym aby po kliknięciu w logo w headerze przeniosło mnie na stronę główną

**Comment by LukaszPietrzykowski16** [comment]
Dodałem przekierowanie na '/'
Również dałem to na cały element header (po kliknięciu w krowę i w napis przekierowuje nas)
