### ISSUE TITLE
[FE][U] Dodać footer do home componentu

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#122]
### Informacje
Mamy gotowy footer który trzeba dodać do wioku home, żeby był widoczny cały czas dla zalogowanego użytkownika

### Kryteria akceptacji
- [ ] Jako zalogowany użytkownik widzę footer na samym dole strony

**Comment by GBN6** [comment]
@PawelJurga 

### Preview
[LINK](https://feature-98-wyswietl-zadeklarowych-uczestnikow--moovelo-envelo.netlify.app/theme)

**Comment by PawelJurga** [comment]
- [x] Jako zalogowany użytkownik widzę footer na samym dole strony
- **widok footera bez zastrzeżeń** 
**Rekomenduję zakończenie taska :)**
