### ISSUE TITLE
[FE][bugfix] Poprawić wyświetlanie blura w nawigacji zalogowanego użytkownika

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#123]
### Informacje
Jak klikamy na ikonkę hamburgera to widać wysuwający się blur, a lepiej, żeby się po prostu pojawiał. Jest też on za długi i rozszerza on niepotrzebnie stronę przez co robi się scroll.
Dodatkowo trzeba dodać cursor pointer na hover ikonek hamburgera i krzyżyka.

### Kryteria akceptacji
- [ ] cursor pointer na ikonkach hamburgera i krzyżyka
- [ ] blur z wysokością maksymalną odpowiadającą wysokości ekranu
- [ ] blur bez transition na wysuwanie się, tylko żeby się pojawiał

**Comment by LukaszPietrzykowski16** [comment]
Preview: https://deploy-preview-134--moovelo-envelo.netlify.app/create-event/type
figma: https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613029%3A10594&t=f2yOURuucm6CfrIG-0

**Comment by PawelJurga** [comment]
- [x]  cursor pointer na ikonkach hamburgera i krzyżyka

- [x] blur z wysokością maksymalną odpowiadającą wysokości ekranu

- [x] blur bez transition na wysuwanie się, tylko żeby się pojawiał
**Rekomenduję zakończenie taska :)**
