### ISSUE TITLE
[FE][U][V] Implementacja auth guarda

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#124]
### Informacje
Implementacja auth guarda który ma sprawdzić, czy user jest już zalogowany i który chroni routy które wymagają aby użytkownik był zalogowany

### Kryteria akceptacji
- [ ] guard na początku startowania aplikacji powinien sprawdzić, czy użytkownik jest zalogowany
- [ ] jeżeli użytkownik nie jest zalogowany to guard nie powinien dać dostępu do wszystkich stron poza stroną do logowania się oraz widoku eventów zewnętrznych
- [ ] Jeżeli użytkownik jest zalogowany to guard powinien sprawdzić czy zapisany token jest ważny
- [ ] Jeżeli token jest nieważny to user powinien zostać wylogowany oraz przeniesiony na stronę logowania
- [ ] Jeżeli token jest ważny to guard powinien pobrać user id, typ konta i odświeżony token oraz przenieść użytkownika na stronę główną aplikacji 
- [ ] Jeżeli Visitor (użytkownik niezalogowany) chce przejść na stronę wymaganą zalogowania powinien zostać przeniesiony na stronę logowania
- [ ] Jeżeli zalogowany użytkownich chce przejsc na stronę logowania to powinien być przeniesiony na stronę główną aplikacji

**Comment by LukaszPietrzykowski16** [comment]
Jeżeli użytkownik wpisze błędne hasło lub email i server zwróci 404 przydałoby się wyświetlić komunikat w stylu 'Błędny email/hasło'.

**Comment by maciekw129** [comment]
### Informacje
Task: #124 
[preview](https://feature-124-implementacja-auth-guarda--moovelo-envelo.netlify.app/)

### Przykładowa baza db.json z wykorzystaniem json-auth
w tej bazie możemy się zalogować za pomocą email: ee@email.com, hasło: password123
```json
{
  "users": [
    {
      "email": "ee@email.com",
      "password": "$2a$10$HP.tDa2HUow4sfKQ0tpVzOj/h.d1/0e8smeRkhe5xvS1MSlkMrXwi",
      "type": "user",
      "id": 1
    }
  ]
}
```

**Comment by PawelJurga** [comment]
**Na chwilę obecną da się zalogować i wylogować z aplikacji. Problemem jest to, że każda sesja generuję token, który w żaden sposób nie jest weryfikowany, przykład:
Użytkownik w ciągu minuty loguje się oraz wylogowuje z aplikacji 10 razy. W tym czasie generowane jest 10 tokenów. Kiedy użytkownik, który jest obecnie zalogowany podmieni token na jakiś wcześniej wygenerowany system nie informuję go, że token jest nieaktualny. Należy to rozumieć tak, że system tylko odczytuję dane z tokena zaszyfrowane w formacie Base64. W mojej opinii każdorazowe logowanie powinno dezaktywować stary token a system powinien to weryfikować.**

**Comment by PawelJurga** [comment]
Po konsultacji wewnątrz zespołu oraz z mentorem na tym etapie wytwarzania aplikacji to rozwiązanie jest odpowiednie. Ewentualne modyfikację do tej funkcjonalności nastąpią po stronie Backendu.
**Rekomenduję zakończenie taska :)**
