### ISSUE TITLE
[FE][U] User może wypełnić formularz stworzenia wydarzenia

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#14]
### Story
Jako User chciałbym móc wypełnić formularz stworzenia wydarzenia
### Dodatkowe informacje
Na tym etapie nie dodajemy funkcjonalności proponowania nowych kategorii wydarzeń adminowi, wyboru kategorii, wyboru grupy, dodawania załączników i hashtagów oraz tworzenia wydarzenia w bazie danych.
### Makiety
[Makiety](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=0%3A394&t=GwaruJDVjcY1V4J0-0)
[Design system](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=77%3A432&t=GwaruJDVjcY1V4J0-0)
### Taski blokujące
- #2 
## Kryteria akceptacji
- [x] Jako User w momencie przejścia na stronę tworzenia wydarzenia, chcę mieć możliwość wyboru czy wydarzenie jest prywatne
- [x] Jeżeli wybiorę, że wydarzenie jest prywatne to mam być przeniesiony do formularza wydarzenia
- [x] Jeżeli wybiorę, że wydarzenie nie jest prywatne to mam zostać przeniesiony do widoku, gdzie mam możliwość wyboru czy wydarzenie jest grupowe
- [x] Jeżeli wybiorę, że wydarzenie jest grupowe to mam być przeniesiony do formularza wydarzenia
- [x] Jeżeli wybiorę, że wydarzenie nie jest grupowe to mam zostać przeniesiony do widoku, gdzie mam możliwość wyboru czy wydarzenie jest firmowe. Wybór każdej opcji ma mnie przenieść do formularza wydarzenia
- [x] Jako User w formularzu chciałbym mieć możliwość wpisania tytułu wydarzenia, które nie musi być unikalne. Minimalna długość tytułu ma wynosić 4 znaki, maksymalna 100
- [x] Walidacja: za mało znaków lub puste pole:  *Tytuł musi składać się minimum z 4 znaków.*
- [x] Walidacja: za duża ilość znaków:  *Tytuł może posiadać maksymalnie 100 znaków.*
- [x] Jako User w formularzu chciałbym mieć możliwość zaznaczenia, czy potwierdzenie jest obowiązkowe
- [x] Jako User w formularzu chciałbym mieć możliwość wpisania daty rozpoczęcia wydarzenia
- [x] Walidacja: data jest w przeszłości: *Data nie może być przeszła*
- [x] Jako User w formularzu chciałbym mieć możliwość wpisania miasta
- [x] Walidacja: puste pole: *Miasto nie może być puste*
- [x] Jako User w formularzu chciałbym mieć możliwość wpisania ulicy
- [x] Walidacja: puste pole: *Ulica nie może być pusta*
- [x] Jako User w formularzu chciałbym mieć możliwość wpisania numeru ulicy
- [x] Walidacja: puste pole: *Numer ulicy nie może być pusty*
- [x] Jako User w formularzu chciałbym mieć możliwość wpisania numeru mieszkania
- [x] Jako User w formularzu chciałbym mieć możliwość wpisania opisu wydarzenia. Minimalna długość ma wynosić 4 znaki, a maksymalna 4000 znaków
- [x] Walidacja: za mało znaków lub puste pole: *Opis musi składać się z minimum 4 znaków*
- [x] Walidacja: za dużo znaków: *Opis musi składać się z maksymalnie 4000 znaków*

**Comment by maciekw129** [comment]
Podczas tego taska poprawiłem także globalne style (zamiana @import na @use) oraz dodałem globalne klasy: main-container do ustawienia strony oraz blue-container dla niebieskich sekcji

**Comment by PawelJurga** [comment]
Dla tego taska **wszystkie kryteria akceptacji zostały spełnione**. Uwagi dotyczące kosmetyki, które zostaną wprowadzone w kolejnym zadaniu przekazałem w wiadomości prywatnej na Discord.
