### ISSUE TITLE
[Fe] [U] User - przegląda grupy

### ISSUE THREAD

**Issue by LukaszPietrzykowski16** [akademia-envelo-3/moovelo-front#17]
### Story 
User może przegląda grupy

### Dodatkowe informacje
- User przegląda grupy które są pobierane z endpointa /groups, wyświetlany jest tytuł, krótki opis, oraz przycisk dołączenia do grupy

### Link do Makiet:
https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613026%3A6275&t=jnOwK4MYswdWwiEY-0

### Kryteria akceptacji:
- [ ] Wyświetlenie listy grup

**Comment by maciekw129** [comment]
Trzeba to przerobić na taska obejmującego tylko wyświetlanie listy grup. Pojedyncza grupa i dołączanie do grup są osobnymi taskami

**Comment by PawelJurga** [comment]
- [x] Wyświetlenie listy grup

W przypadku dodania większej ilości znaków w pola "name" i "discription" formularz się "rozjeżdża". Na etapie implamentacji logiki to tego widoku należy ustalić warunki brzegowe dla tych pól. W trakcie testów zaobserwowałem, że w przypadku wpisania tekstu o długości np. 100 znaków w pole "discription" oraz np. 30 w pole "name" przemieszczeniu ulega "plusik". W związku z tym, aby uniknąć przemieszczania się tego elementu proponuję aby warunki brzegowe zostały ustalone następująco:
- **"name": min 3 max 20**
-  **"discription" : min 3 max 40**
Takie rozwiązanie spowoduję, że tekst umieszczony w tych polach będzie znajdował się w jednej linijce i nie spowoduje rozjechania się widoku (szczególnie w wersji mobilnej). Dla wersji web te wartości mogą być odpowiednio wyższe.

**Powyższe nie stanowi kryterium akceptacji, a jest jedynie spostrzeżeniem, które należy wziąść pod uwagę podczas tworzenia backendu dla tego widoku, dlatego rekomenduję zakończenie taska :)**
