### ISSUE TITLE
[FE] [U] Zrobienie widoku tworzenia wydarzenia - wszystkie wariacje

### ISSUE THREAD

**Issue by JRRBorkowski** [akademia-envelo-3/moovelo-front#19]
Story
Jako User mam dostęp do ekranów tworzenia wydarzeń zmieniających się zależnie od wybranych opcji.

Dodatkowe informacje
Na tym etapie tworzymy jedynie wariacje ekranu zależne od wybranych opcji:
- Ekran pytania o prywatność wydarzenia
- Ekran tworzenia wydarzenia prywatnego
- Ekran pytania o tworzenie wydarzenia dla grupy
- Ekran tworzenia wydarzenia grupy
- Ekran pytania o tworzenie wydarzenia dla firmy
- Ekran tworzenia wydarzenia firmowego
- Ekran tworzenia wydarzenia publicznego

Link do Makiet:
https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613040%3A7913&t=YIK44DL31ore4DQE-0

Kryteria akceptacji:

- [ ]  User wybiera przycisk stworzenia nowego wydarzenia.
- [ ]  User wyświetla ekran zapytania o prywatność wydarzenia.
- [ ]  w przypadku pozytywnej odpowiedzi User zostaje przeniesiony na stronę tworzenia wydarzenia prywatnego
- [ ]  User jest zapytany o tworzenie wydarzenia dla grupy.
- [ ]  w przypadku pozytywnej odpowiedzi User zostaje przeniesiony na stronę tworzenia wydarzenia dla grupy
- [ ]  User jest zapytany o tworzenie wydarzenia dla firmy
- [ ]  w przypadku pozytywnej odpowiedzi User zostaje przeniesiony na stronę tworzenia wydarzenia dla firmy
- [ ]  w przypadku negatywnej odpowiedzi User zostaje przeniesiony na stronę tworzenia wydarzenia zewnętrznego

**Comment by maciekw129** [comment]
Mamy cały milestone z tworzenia wydarzenia, ten task jest w dużej mierze zdublowany z tym: #14

**Comment by JRRBorkowski** [comment]
Przerobione na milestone
