### ISSUE TITLE
[FE][U] Jako User chciałbym mieć możliwość wyboru kategorii podczas tworzenia wydarzenia 

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#27]
### Story
Jako User podczas tworzenia wydarzenia chciałbym mieć możliwość wybrania kategorii wydarzenia z rozwijanej listy kategorii.
### Dodatkowe informacje
Na tym etapie nie dodajemy funkcjonalności proponowania nowych kategorii wydarzeń adminowi
Wybór kategorii powinien częścią formularza stworzenia wydarzenia.
### Makiety
[Makieta](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613157%3A25471&t=ezvh3VGhOEkxJEOn-0)
[Design system](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=77%3A432&t=GwaruJDVjcY1V4J0-0)
### Taski blokujące
- #2 
- #14 
### Taski powiązane
- #30 
### Endpointy
GET api/v1/eventCategories
## Kryteria akceptacji
- [x] Jako User chce mieć możliwość rozwinięcia listy dostępnych kategorii za pomocą przycisku "Wybierz kategorię"
- [x] Jako User chce mieć możliwość wyboru konkretnej kategorii z listy poprzez kliknięcie w nią
- [x] Jako User mam mieć możliwość zmiany wyboru kategorii poprzez kliknięcie przycisku z napisem wybranej już kategorii zamiast napisu "Wybierz kategorię" i ponowne wybranie nowej kategorii z listy

**Comment by LukaszPietrzykowski16** [comment]
Do 3 kryterium akceptacji: Wygląd został zmieniony ponieważ material zapewnia nam selecta który nam załatwia wybór kategorii, więc postanowiliśmy go zmienić, aby też był spójny z grupami.

**Comment by LukaszPietrzykowski16** [comment]
Preview: https://deploy-preview-127--moovelo-envelo.netlify.app/create-event/details

Baza danych JSON:
"eventCategories": [ { "name": "piwo" }, { "name": "piłkarzyki" }, { "name": "wyjścia do baru" }, { "name": "szydełkowanie" }, { "name": "plaża" } ]

**Comment by PawelJurga** [comment]
- [x] Jako User chce mieć możliwość rozwinięcia listy dostępnych kategorii za pomocą przycisku "Wybierz kategorię"

- [x] Jako User chce mieć możliwość wyboru konkretnej kategorii z listy poprzez kliknięcie w nią

- [x] Jako User mam mieć możliwość zmiany wyboru kategorii poprzez kliknięcie przycisku z napisem wybranej już kategorii zamiast napisu "Wybierz kategorię" i ponowne wybranie nowej kategorii z listy
**Kryteria akceptacji spełniono :)**

**UWAGI**

- Widok formularza "Wybierz kategorię" daje możliwość wyświetlania inputu o maksymalnej długości 29 znaków. Przy tworzeniu kategorii należy uwzględnić to ograniczenie lub dostosować widok formularza do ewentualnych nazw o większej długości. Temat do uzgodnienia z zespołem Front.


![Image](https://user-images.githubusercontent.com/121928858/215051684-574e3133-fc12-4434-ad72-334e73fc2d4b.png)

**Comment by LukaszPietrzykowski16** [comment]
Ustaliliśmy z zespołem front że ograniczymy ilość znaków przy kategorii do 29. Zamieściłem odpowiedni komentarz w dokumentacji.

**Comment by PawelJurga** [comment]
W związku z powyższym komentarzem **rekomenduję zakończenie taska.**
