### ISSUE TITLE
[FE][V] Visitor Stworzenie formularza do zapisania się na wydarzenie

### ISSUE THREAD

**Issue by LukaszPietrzykowski16** [akademia-envelo-3/moovelo-front#3]
### Story 
Visitor może wpisać do formularza zapisu swoje imię nazwisko i mail

### Dodatkowe informacje
Pojawia się formularz z polami:
- imię 
- nazwisko
- e-mail
Jeżeli zostanie wpisany zły e-mail, niewypełnione pole, bądź zbyt długa nazwa zostanie wyświetlony odpowiedni komunikat
### Link do Makiet:
https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=0%3A394&t=F55JsmoUlSU5algE-0

### Kryteria akceptacji:
- [x] Stworzenie formularza z 3 polami 
- [x] Stworzenie buttona z zapis się
- [x] Wyświetlenie komunikatu o błędzie

**Comment by maciekw129** [comment]
Trzeba tutaj doprecyzować w kryteriach akceptacji informacje odnośnie walidacji: max i min liczba znaków, dozwolone znaki specjalne, określić konkretne komunikaty o błędach

**Comment by maciekw129** [comment]
Trzeba rozbić tego taska na stworzenie samego formularza oraz osobno dodanie funkcjonalności zapisu na wydarzenie poprzez post do api
