### ISSUE TITLE
Stworzenie searchbara

### ISSUE THREAD

**Issue by LukaszPietrzykowski16** [akademia-envelo-3/moovelo-front#40]
### Story 
Wszyscy aktorzy oprócz visitora, z dowolnej części aplikacji mogą wyszukać w searchbarze:
- wydarzenie 
- grupę

### Szczegóły 

Po wpisywaniu do searchbara, idzie strzał do API, a backend zwraca podpowiedzi do wyszukiwanych słów (wydarzenie oraz grupy)

### Powiązane
#11 

### Link do Makiet:
https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613157%3A25482&t=hDaRjAavkG82wMF6-0

### Kryteria akceptacji:
- [x] obsługa wpisania liter z czekaniem za użytkownikiem kilka milisekund
- [x] Strzał do API
- [x] Backend zwraca wydarzenie/grupę
- [x] Frontend wyświetla listę wydarzen/grup
- [ ] Można wybrać wydarzenie/grupę i przekierować do danego wydarzenia/grupy

**Comment by maciekw129** [comment]
Przekierowanie do strony eventu / grupy będzie implementowane w osobnym tasku

**Comment by maciekw129** [comment]
W ramach tego taska dodałem searchbara do komponentu navbara usera oraz wrzuciłem go do strony home
