### ISSUE TITLE
[FE][V6] Jako visitor chcę wypełnić formularz by się zalogować

### ISSUE THREAD

**Issue by GBN6** [akademia-envelo-3/moovelo-front#5]
### Story
Jako visitor chciałbym zalogować się w aplikacji poprzez przesłanie formularza logującego. Podaje swój adres email oraz hasło, które zostaje zweryfikowane przez system.

### Dodatkowe informację
Po udanym zalogowaniu przekieruj do strony głównej usera 

---

### Makiety
![Widok formularza logowania](https://user-images.githubusercontent.com/101929151/210374854-bac7041b-c482-4487-a931-8c763a250f91.png)
![Widok formularza z błędem](https://user-images.githubusercontent.com/101929151/210376261-9f4c294a-b457-431e-8067-62d8c343d372.png)
[Makiety](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=0%3A394&t=AO8NFooPtUMNwfKI-0)

### Taski powiązane
#63 

### Endpointy
[Swagger - auth](#) `POST` `/auth`

### Kryteria akceptacji

- [x] Jako użytkownik chciałbym wpisać swój email. 
- [x] pole wymagane, maksymalna długość 100 znaków, email podany w odpowiednim formacie `nazwa@domena.com`. Przykład `test@test.pl`
- [x] Jako użytkownik chciałbym zobaczyć komunikat walidacyjny dla pola email:
- [x] błędny format lub puste pole: "Podaj poprawny adres email według wzoru: nazwa@domena.pl
- [x] Jako użytkownik chciałbym wprowadzić swoje hasło
- [x] Jako użytkownik chciałbym zobaczyć komunikaty walidacyjne po kliknięciu przycisku `zaloguj`, gdy formularz zawiera błędy lub po evencie blur na input w momencie błędnego wypełnienia inputa
 - [ ] ~Jako użytkownik mogę wysłać formularz poprzez kliknięcie przycisku `zaloguj` lub naciśnięcia klawisza `Enter`~
 - [ ]  ~Jako użytkownik chciałbym zostać przekierowany na stronę główną po udanej autoryzacji~
- [ ]  ~Jako użytkownik chciałbym zobaczyć komunikat o błędnej autoryzacji.~
- [ ] ~brak autoryzacji: "Nazwa użytkownika bądź hasło są niepoprawne. Spróbuj ponownie"~

**Comment by maciekw129** [comment]
Trzeba rozbić tego taska na stworzenie samego formularza oraz osobno funkcjonalność autoryzacji

**Comment by annkierl** [comment]
Komponent posiada metodę checkValidationAndAuth(), która będzie rozwijana w dalszej części. 
Należy również powrócić do styli - implementacja styli materialowych dla spójności.
Zostało to dodane w tasku powiązanym #63
