### ISSUE TITLE
[FE] Stworzyć komponent loadera

### ISSUE THREAD

**Issue by maciekw129** [akademia-envelo-3/moovelo-front#55]
### Informacje
Stworzyć komponent zawierający animację ładowania zgodną z makietami

### Makiety
[Makieta](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613126%3A10517&t=iqOHIfChxZQENr96-0)

### Kryteria akceptacji
- [x] Komponent powinien być zgodny z makietami w figmie
- [x] Animacja powinna być zapętlona w nieskończoność

**Comment by LukaszPietrzykowski16** [comment]
Zmieniłem animację z linear na ease-out, ponieważ wygląda lepiej.
