### ISSUE TITLE
[FE][U][EO][V][A] Zrobienie widoku pojedynczego wydarzenia

### ISSUE THREAD

**Issue by JRRBorkowski** [akademia-envelo-3/moovelo-front#6]
### Story
Aktorzy mogą przeglądać informacje dotyczące pojedynczego wydarzenia.

### Dodatkowe informacje:
Task nie uwzględnia funkcjonalności komentarzy, ankiet oraz przycisków: "Biorę udział", "Zastanawiam się" oraz "Rezygnuję" oraz komponentu zliczania ilości osób rezygnujących, zastanawiających się oraz osób które zrezygnowały z wydarzenia.
Nie uwzględnia także menu ukazującego się po kliknięciu w zębatkę w przypadku Admina, Event Ownera

### Link do Makiet:
[Widok Visitora](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613079%3A9463&t=YIK44DL31ore4DQE-0)
[Widok Usera](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613030%3A7950&t=YIK44DL31ore4DQE-0)
[Widok Admina](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613027%3A3799&t=YIK44DL31ore4DQE-0)
[Widok Event Ownera](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613028%3A13393&t=YIK44DL31ore4DQE-0)
[Widok Group membera](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613081%3A9240&t=YIK44DL31ore4DQE-0)

### Taski powiązane
- #98 
- #23 
- #48
- #47 
- #13 

### Endpointy 
{
  "events": [
    {
      "id": 1,
      "eventInfo": {
        "isConfirmationRequired": true,
        "limitedPlaces": 10,
        "eventParticipationStats": {
          "accepted": 9,
          "pending": 7,
          "rejected": 5
        },
        "isPrivate": true,
        "group": {
          "id": 123,
          "name": "piwosze"
        },
        "cycleLenght": 3,
        "name": "pubowe spotkania",
        "category": {
          "id": 1,
          "name": "pub"
        },
        "startDate": "20.02.2023",
        "hour": "09:22",
        "location": {
          "id": 1,
          "altitude": 2.33,
          "latitude": 3.44,
          "postCode": "30-222",
          "city": "Warszawa",
          "street": "Rybna",
          "streetNumber": "8",
          "apartmentNumber": "1"
        },
        "description": "  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, exercitationem nam. Asperiores quo, saepe dolor similique eaque culpa maiores! Nostrum fugit iste, maiores veniam omnis at. Ducimus ex necessitatibus assumenda? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, exercitationem nam. Asperiores quo, saepe dolor similique eaque culpa maiores! Nostrum fugit iste, maiores veniam omnis at. Ducimus ex necessitatibus assumenda? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, exercitationem nam. Asperiores quo, saepe dolor similique eaque culpa maiores! Nostrum fugit iste, maiores veniam omnis at. Ducimus ex necessitatibus assumenda? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, exercitationem nam. Asperiores quo, saepe dolor similique eaque culpa maiores! Nostrum fugit iste, maiores veniam omnis at. Ducimus ex necessitatibus assumenda? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, exercitationem nam. Asperiores quo, saepe dolor similique eaque culpa maiores! Nostrum fugit iste, maiores veniam omnis at. Ducimus ex necessitatibus assumenda? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, exercitationem nam. Asperiores quo, saepe dolor similique eaque culpa maiores! Nostrum fugit iste, maiores veniam omnis at. Ducimus ex necessitatibus assumenda?",
        "hashtags": [
          {
            "id": 1,
            "value": "spotkanie"
          },
          {
            "id": 2,
            "value": "piwo"
          }
        ]
      }
    },
    {
      "id": 2,
      "eventInfo": {
        "isConfirmationRequired": false,
        "limitedPlaces": 0,
        "eventParticipationStats": {
          "accepted": 30,
          "pending": 1,
          "rejected": 12
        },
        "isPrivate": false,
        "group": "group",
        "groupInfo": {
          "id": 14,
          "name": "planszówkowicze"
        },
        "cycleLenght": 0,
        "name": "Spotkanie na planszówki",
        "category": {
          "id": 2,
          "name": "planszówki"
        },
        "startDate": "14.09.2023",
        "hour": "14:20",
        "location": {
          "id": 1,
          "altitude": 2.43,
          "latitude": 7.44,
          "postCode": "20-333",
          "city": "Gdańsk",
          "street": "Liliowa",
          "streetNumber": "3",
          "apartmentNumber": "2"
        },
        "description": "",
        "hashtags": [
          {
            "id": 1,
            "value": "boardgames"
          }
        ]
      }
    }
  ]
}

### Kryteria akceptacji:
- [x]  W przypadku wydarzenia z obowiązkowym zapisem na górze widoku powinien pojawić się napis, że jest to tego typu wydarzenie oraz liczba pozostałych miejsc zgodnie z makietami
- [x]  W przypadku wydarzenia prywatnego na górze widoku powinien pojawić się napis, że jest to tego typu wydarzenie, zgodnie z makietami
- [x]  W przypadku wydarzenia grupowego na górze widoku powinien pojawić się napis, że jest to tego typu wydarzenie, zgodnie z makietami
- [x]  W przypadku wydarzenia cyklicznego pod obrazkiem powinien pojawić się napis, że jest to tego typu wydarzenie, zgodnie z makietami

**Comment by maciekw129** [comment]
W tasku trzeba przerobić kryteria akceptacji i stworzyć taski funkcjonalności komentarzy, ankiet oraz przycisków: "Biorę udział", "Zastanawiam się" oraz "Rezygnuję" oraz komponentu zliczania ilości osób rezygnujących, zastanawiających się oraz osób które zrezygnowały z wydarzenia.

**Comment by PawelJurga** [comment]
@annkierl oznacz mnie jak task przejdzie do QA

**Comment by annkierl** [comment]
@PawelJurga

**Comment by PawelJurga** [comment]
- [x] W przypadku wydarzenia z obowiązkowym zapisem na górze widoku powinien pojawić się napis, że jest to tego typu wydarzenie oraz liczba pozostałych miejsc zgodnie z makietami

- [x] W przypadku wydarzenia prywatnego na górze widoku powinien pojawić się napis, że jest to tego typu wydarzenie, zgodnie z makietami

- [x] W przypadku wydarzenia grupowego na górze widoku powinien pojawić się napis, że jest to tego typu wydarzenie, zgodnie z makietami

- [x] W przypadku wydarzenia cyklicznego pod obrazkiem powinien pojawić się napis, że jest to tego typu wydarzenie, zgodnie z makietami

**Kryteria akceptacji spełniono :)**

## W trakcie testowania zauważyłem następujące błędy/problemy

 **- brak napisów "weźmie udział", "zastanawia się", "zrezygnowało" pod liczbą tych osób**
 **- brak buttona "skopiuj link"**
 

![Image](https://user-images.githubusercontent.com/121928858/214502822-e46eb002-1031-42ec-9eae-928324c03351.png)

**- zawartości labelków (?,x,✓) powinny się znajdować na środku komponentu** 


![Image](https://user-images.githubusercontent.com/121928858/214503541-209f067a-dcd6-40ba-bc16-919d48d29c10.png)

**- wprowadzenie wielu hashtagów powoduje rozjechanie się widoku, nie powinny być wyświetlane w linii w nieskończoność, podobnie jest w przypadku np. kategorii** (screen poniżej)
**- opis wydarzenia - warto się zastanowić nad justowaniem, w mojej opinii będzie to wyglądać lepiej**
**- w przypadku pól nazwy grupy, nazwy wydarzenia, adresu oraz kategorii należy się zastanowić nad zablokowaniem znaków angielskich (ale to bardziej na przyszłość dla backendu)**


![Image](https://user-images.githubusercontent.com/121928858/214508199-d022d3c7-b22e-4197-88a2-1c1dfddb7952.png)

**Comment by PawelJurga** [comment]
@annkierl 

**Jeszcze jest jeden moim zdaniem błąd. Pojawia się cursor pointer jak się najedzie na :**


![Image](https://user-images.githubusercontent.com/121928858/214547544-69f356cc-64a5-4f26-b65c-3af366d7f0d8.png)

**Comment by annkierl** [comment]
- faktycznie brak podpisów,  okazało się, że jest task na dodanie tych buttonów do eventu. Więc usunęłam je na ten moment.
 Link do zadania: Zadanie do realizacji w tym spritncie 
https://github.com/akademia-envelo-3/moovelo-front/issues/98
- skopiuj link pojawi się w momencie jak wydarzenie będzie publiczne - dla ludzi z zewnątrz firmy. Więc to jest tylko trzeba ustawić flagę. 
- hashtagi ogarnięte - zawijają się/przechodzą do następnej linii. 
- justowanie ogarnięte 
[ uwaga: ilość znaków kategorii ustalana jest tak czy siak przy wprowadzaniu danych. Jednak obsłużyłam, żeby text się zawijał]
- Zgodnie z naszą rozmową zaktualizowałam treść db.jsona w treści taska. 
@PawelJurga

**Comment by PawelJurga** [comment]
@annkierl 

**Nazwa wydarzenia się trochę rozjeżdża. Trzeba by zrobić takie rozwiązanie, aby w przypadku zbyt długiej nazwy przenosiło linie niżej.**


![Image](https://user-images.githubusercontent.com/121928858/214573838-4f494305-2dc3-442a-8a02-d81f221adf22.png)

**Dobrze żeby ten tekst był wyjustowany** 


![Image](https://user-images.githubusercontent.com/121928858/214574579-0a173cbe-65d8-4f1f-b0dd-7104bf9fab1d.png)
**Reszta jest super :)**

**Comment by annkierl** [comment]
@PawelJurga Jest już - dosłownie 2 linijki kodu do dopisania było. :)

**Comment by PawelJurga** [comment]
**Restest**
 **Błędy zgłoszone w komentarzu powyżej zostały wyeliminowane.**


![Image](https://user-images.githubusercontent.com/121928858/214776524-6d229750-da4a-4436-a490-803e0b3051c2.png)



![Image](https://user-images.githubusercontent.com/121928858/214776565-484d57b5-ea1f-4efd-abe3-bd0b302869ae.png)

**Rekomenduję zakończenie taska :)**
