### ISSUE TITLE
[FE] Visitor Widok wydarzenia zewnętrznego

### ISSUE THREAD

**Issue by LukaszPietrzykowski16** [akademia-envelo-3/moovelo-front#7]
### Story 
Visitor może widzieć widok wydarzenia zewnetrznego i zapisać się na nie

### Dodatkowe informacje
Visitor po wejściu w linka którego dostał widzi: 
- Navbar z logiem i przyciskiem zaloguj po kliknięciu którego zostaje przeniesiony do widoku zalogowania
- Tytuł wydarzenia, typ zapisu, liczbę miejsc, statystki osób biorących udział, zdjęcie powiązane z kategorią, kategorię, datę, adres, opis, hashtagi, mapę, przycisk zapisz się, footer
- Może się zapisać na wydarzenie za pomocą przycisku 'Zapisz się'

### Link do Makiet:
https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=0%3A394&t=F55JsmoUlSU5algE-0

##Powiązane:
#6  Pojedyńcze wydarzenie (duplikacja pracy???) (różni się navbarem, oraz nie widać komentarzy i ankiety)
#3  Formularz

### Kryteria akceptacji:
- [ ] Wyświetlenie navbara z logiem oraz przyciskiem zaloguj
- [ ] Wyświetlenie komponentu ze zdjęciem, tytułem, datą, kategorią, Adresem
- [ ] Wyświetlenie opisu oraz hashtagów
- [ ] Wyświetlenie mapy
- [ ] Wyświetlenie formularzy

**Comment by maciekw129** [comment]
Wydaje mi się, że nie potrzebujemy tego taska. Ten widok obejmuje task: #6
