### ISSUE TITLE
[FE][Makiety]Dodać funkcjonalność zapraszania na wydarzenie

### ISSUE THREAD

**Issue by annkierl** [akademia-envelo-3/moovelo-front#92]
### Cel:
Celem jest  dodanie buttona do wydarzeń, który pozwala na zapraszanie innych użytkowników.
Po kliknięciu na button ma się pojawić szukajka użytkowników.
Task powiązany 
- #91

**Comment by JRRBorkowski** [comment]
Przycisk został już stworzony, należy jedynie dodać ekran szukajki
