### ISSUE TITLE
[FE][Makieta] Dodanie wyświetlania liczby członków grupy do makiety i do komponentu. 

### ISSUE THREAD

**Issue by annkierl** [akademia-envelo-3/moovelo-front#93]
### STORY 
Przy wyświetlaniu listy grup użytkownik widzi liczbę ich członków
### Kryteria akceptacji:
- [x] Dodanie widoku do makiet
- [x] Powiadomienie Backendu o tym, że potrzebujemy liczby grup w naszym endpoint dla grup
- [x] Dodanie funkcjonalności do komponentu.

**Comment by GBN6** [comment]
Preview 
[LINK - Pojedyncza grupa w liscie](https://feature-93-wyswietl-liczbe-czlonkow-grupy--moovelo-envelo.netlify.app/theme)
