### ISSUE TITLE
[FE] [U] Wyświetla listę zadeklarowanych uczestników - biorę udział/zastanawiam się/odrzucam

### ISSUE THREAD

**Issue by JRRBorkowski** [akademia-envelo-3/moovelo-front#98]
### Story
Jako user chciałbym zobaczyć zadeklarowanych uczestników wydarzenia. Po kliknięciu na odpowiednią grupę wyświetli się lista użytkowników, którzy wybrali daną opcję.

### Dodatkowe informacje
Po przejściu na stronę wydarzenia klikam na przyciski odpowiadający odpowiedniej opcji biorę udział, zastanawiam się, bądź nie jestem zainteresowany, po czym zostaje wyświetlona lista osób, które wybrały tą opcję.

### Makiety
[Widok wydarzenia](https://www.figma.com/file/VwoFt9OUGvu0j4IABdGZHs/Moovelo?node-id=613030%3A7950&t=YIK44DL31ore4DQE-0)

### Taski powiązane
- #23 
- #13 
- #48 
- #47 
- 
### Endpointy
GET events/{eventId}/users?status = accepted
GET events/{eventId}/users?status = rejected
GET events/{eventId}/users?status = pending

```json
{
  "eventId": 1,
  "eventInfo": {
    "isConfirmationRequired": true, 
    "limitedPlaces": 0 | 10,
    "eventParticipationStats": {
      "accepted": 10,
      "pending": 12,
      "rejected": 11
    },
    "isPrivate": false,
    "group": null | group,
    "group": {
      "id": 123,
      "name": "grupa1"
    },
    "cycleLenght": 0,
    "name": "",
    "category": {
       "id": 1,
       "name": ""
    },
    "startDate": "",
    "hour": "",
    "location": {
      "id": 1,
      "altitude": 2.33,
      "latitude": 3.44,
      "postCode": "",
      "city": "",
      "street": "",
      "streetNumber": "",
      "apartmentNumber": ""
    },
    "description": "",
    "hashtags": [
       {
          "id": 1,
           "value": "sport"
        }
     ],
  }
}

{
    "users": [
        {
            "id": 1,
            "firstname": "",
            "lastname": ""
        }
    ],
    "visitors": [
        {
            "firstname":"",
            "lastname":""
        }
    ]
}

```

### Kryteria akceptacji
 - [ ] Jako user po kliknięciu w przycisk liczby osób biorących udział w wydarzeniu chciałbym zobaczyć listę tych osób pod spodem
 - [ ] Jako user po kliknięciu w przycisk liczby osób zastanawiających się czy brać udział w wydarzeniu chciałbym zobaczyć listę tych osób pod spodem
 - [ ] Jako user po kliknięciu w przycisk liczby osób które zrezygnowały z udziału w wydarzeniu chciałbym zobaczyć listę tych osób pod spodem

**Comment by GBN6** [comment]
@PawelJurga 

Co do komponentu zmieniła się jego koncepcja i w aktualnej wersji nie potrzebuje już wysyłania zapytań do API, tylko jest "dumb component", który otrzymuje dane od rodzica w związku z czym baza danych z taska jest nie potrzebna. 

### Preview
[LINK](https://feature-98-wyswietl-zadeklarowych-uczestnikow--moovelo-envelo.netlify.app/theme)

Komponent `Lista uczestników eventu`

**Comment by PawelJurga** [comment]
- [x] Jako user po kliknięciu w przycisk liczby osób biorących udział w wydarzeniu chciałbym zobaczyć listę tych osób pod spodem

- [x] Jako user po kliknięciu w przycisk liczby osób zastanawiających się czy brać udział w wydarzeniu chciałbym zobaczyć listę tych osób pod spodem

- [x] Jako user po kliknięciu w przycisk liczby osób które zrezygnowały z udziału w wydarzeniu chciałbym zobaczyć listę tych osób pod spodem

**Kryteria akceptacji spełniono, na tym etapie brak uwag do tego zadania**
**Rekomenduję zakończenie taska :)**
